### ISSUE TITLE
"We were unable to log you in. Please check your credentials." 

### ISSUE THREAD

**Issue by RBGaming** [sibblegp/Storj-Dashboard-Client#10]
when i try to log into storjdash client on windows 10 it says "We were unable to log you in. Please check your credentials." but it works on the website. only thing i can think of is that maybe it wont let me log in because my password uses special characters like !@#$%. and if thats the case how do i password reset?

**Comment by sibblegp** [comment]
That is probably the case.  The submission of special characters isn't very good on the installer yet.  Contact me @gs on community.storj.io and I can reset your password.
