### ISSUE TITLE
Hanging after first msg

### ISSUE THREAD

**Issue by reinierkors** [sibblegp/Storj-Dashboard-Client#11]
Hi, it just says:

> Storj Dashboard Registration

and does nothing.

I assume it's scanning for my storj directory. 

- Why does it have to scan all my files? 
- Why can't I just specify the directory?

**Comment by sibblegp** [comment]
That is when it is scanning for your storjshare executable.  Do you have a lot of files in your /home or /root directories or symlinks?

**Comment by reinierkors** [comment]
I do have a lot of files. Is it possible to specify the directory?
