### ISSUE TITLE
How to check everything is OK ?

### ISSUE THREAD

**Issue by mikebzh44** [sibblegp/Storj-Dashboard-Client#13]
Hi.

I'm running Storj Share GUI and Storj-Dashboard-Client on Windows

I set up Dashboard-Client and I guess it's OK because my node name was registered on my dash board.

But node and dashboard are running for hours and no informations are available :(

https://imgur.com/zgMyR0J

I have check on Windows and Storj-Dashboard service is listed and running.

Can I run it manually to force data upload ? Is there some firewall rule to update ?

Thanks.

**Comment by mikebzh44** [comment]
Try to run storj_service.exe from command line (cmd box opened with my user and as administrator) but fail in both case : 

C:\Program Files\StorJDash Client>storj_service.exe
Traceback (most recent call last):
  File "storjreports\storj_service.py", line 69, in <module>
pywintypes.error: (1063, 'StartServiceCtrlDispatcher', 'Le processus de service n’a pas pu se connecter au contrôleur de service.')
[3252] Failed to execute script storj_service

It's in French but the message says "The service process could not connect to controler service"

Hope it's helpfull

**Comment by mikebzh44** [comment]
Don't know how or why but now data are uploaded on your web site.

**Comment by henrikhjelm** [comment]
check your config for storj.
if your config have storageAllocation: xxxxxxxxx    in bytes
it will not work. (in this version)
my fix was write "2TB" in the config file.

**Comment by mikebzh44** [comment]
Yes, I have allocation in bytes : 
"storageAllocation": "999653638144B"

But everything looks good on the website.

Do I have to edit json file and put 1TB ?

**Comment by henrikhjelm** [comment]
i did have : ""storageAllocation": 2199023255552"

you can try "storj_service.exe debug"
for more info

my post.
https://github.com/sibblegp/Storj-Dashboard-Client/issues/12

**Comment by mikebzh44** [comment]
I have move to Linux ;)
