### ISSUE TITLE
Send_storj_report can't handle configure files contain custom seed list.

### ISSUE THREAD

**Issue by tutux** [sibblegp/Storj-Dashboard-Client#14]
The default format with `"seedList":[]` works fine. However, if you add custom seedlist such like
`"seedList": "storj://[ip.or.hostname]:[port]/[nodeid]"` 
will give an error saying 
`Unable to decode JSON file:`

Workaround:
Put config files without custom seedlists in a different folder and change the configs_directory path to the new folder in
`/etc/storjdash.json`

**Comment by sibblegp** [comment]
Can you PM me on community.storj.io a gist of an example file with this?  I'll see if I can fix it.  Thanks!

**Comment by tutux** [comment]
Just add this line before `"seedList":[],` and it will break:
`"seedList": "storj://45.76.16.187:4001/1d95ce56e1eda7889d4cadba7075190647c9079d",`

(this is an example, you can use any nodes)

**Comment by AricStewart** [comment]
30 second fix.  

https://github.com/sibblegp/Storj-Dashboard-Client/blob/eb0dda4cc79ac9383038095f648ef8c16e374611/storjreports/send_storj_reports.py#L114

Change that line to:
`            if 'https' not in line and 'storj://' not in line:`

Then it starts working again. May not be a 'proper' fix but works great for me.

**Comment by AricStewart** [comment]
Why closed? Was this fixed?
