### ISSUE TITLE
send_storj_reports Unable to decode JSON file

### ISSUE THREAD

**Issue by raptorweb** [sibblegp/Storj-Dashboard-Client#2]
When trying to run send_storj_reports I get the error "Unable to decode JSON file: filename.json" I have tracked this down to line 92 of send_storj_reports.py. It looks like this is cleaning up the https from the bridgeUri value but in doing so it does not put the trailing comma required to have valid JSON. If these assumptions are correct the line

config_contents = re.sub(r'https.*\n', '"', config_contents)

should be changed to 

config_contents = re.sub(r'https.*\n', '",', config_contents)

In my quick REPL test this allowed the json.loads to work correctly

**Comment by Jurisg** [comment]
"bridges":[
    {
      "url": "https://api.storj.io",
      "extendedKey": "xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42"
    }

**Comment by raptorweb** [comment]
I have not regenerated my configs in a few months so an old format could be the issue. Mine looks like this

` // If the seedList is empty, use this bridge to discover seeds
  // Following a transfer, also send an exchange report to this bridge
  "bridgeUri": "https://api.storj.io",
  // Known preferred seeds in form of a storj URI
  // Example: "storj://[ip.or.hostname]:[port]/[nodeid]"
  "seedList": [],
`

**Comment by raptorweb** [comment]
I can confirm that regenerating the configs solves the issue also.

**Comment by madcatsu** [comment]
@raptorweb @Jurisg I had the same issue and it was resolved by recreating my config

**Comment by madcatsu** [comment]
This should now be resolved in the latest commit @Tango43 @raptorweb - I've since created a new config JSON, is anyone else able to confirm this now works with an older config file format?

**Comment by sibblegp** [comment]
I believe the latest version available should solve this problem.  Run 

> sudo pip3 install storjdash --upgrade

 and then try to run reports again.

**Comment by sibblegp** [comment]
@madcatsu @raptorweb @Jurisg Thank you for helping!

**Comment by raptorweb** [comment]
I kept a copy of the old configs, just switched to them and checked looks like the new version is working for me. Thanks
