### ISSUE TITLE
send_storj_reports when run from cron fails

### ISSUE THREAD

**Issue by ubenmackin** [sibblegp/Storj-Dashboard-Client#24]
Every time that the cron job triggers the send_storj_reports, I get the following error:

> Traceback (most recent call last):
>   File "/usr/bin/send_storj_reports", line 11, in <module>
>     load_entry_point('storjdash==0.3.11', 'console_scripts', 'send_storj_reports')()
>   File "/usr/lib/python3.6/site-packages/storjreports/__init__.py", line 5, in run_reports
>     send_storj_reports.main()
>   File "/usr/lib/python3.6/site-packages/storjreports/send_storj_reports.py", line 193, in main
>     examine_configs(settings['configs_directory'])
>   File "/usr/lib/python3.6/site-packages/storjreports/send_storj_reports.py", line 29, in examine_configs
>     storj_node_pairs = examine_storjstatus()
>   File "/usr/lib/python3.6/site-packages/storjreports/send_storj_reports.py", line 76, in examine_storjstatus
>     proc = subprocess.Popen(['storjshare', 'status'], env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>   File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> NotADirectoryError: [Errno 20] Not a directory: 'storjshare'

If I just run the command manually, it runs fine. Not sure why the cron one is causing the above error.

**Comment by S0litaire** [comment]
My storjshare.json file looks something like this :
```
{
    "configs_directory": "/home/<user>/Storjfolder>",
    "server_uuid": "########-####-####-####-############",
    "storjshare_path": "/snap/bin/storjshare"
}
```
The error is in :
 /usr/local/lib/python3.6/dist-packages/storjreports/send_storj_reports.py

line 183 :
`STORJSHARE_PATH = settings['storjshare_path']`
it's reading the whole line and looking for a folder at the end of it, but in the .json, the line is pointing to a executable file NOT a folder so the script throws and error.

Workaround :

in the storjshare.json file change the storjshare_path file to 
`"storjshare_path": "/snap/bin/"`

The `send_storj_reports` script now runs as a cron job with no issues.

**Comment by ubenmackin** [comment]
So it looks like a configuration issue. Tracing back, I see that in register_server.py is where the storjshare.json gets created.

Line 83 is where STORJSHAREPATH is getting set for me, and because it is getting the result of "which", it is returning the full path to the binary.

`STORJSHAREPATH = possible_path`

I think the change is as simple as:

`STORJSHAREPATH = possible_path.split('storjshare')[0][:-1]`

Doing this appears to have fixed the setup routine, and now my cron runs fine.

**Comment by ubenmackin** [comment]
@sibblegp I just created a pull request to fix this issue.
