### ISSUE TITLE
Hide old nodes

### ISSUE THREAD

**Issue by AndreyNazarchuk** [sibblegp/Storj-Dashboard-Client#28]
When I click the little chain icon on a node it shows last seen in the JSON response, can you take that and use it to hide nodes that haven't been seen in a week? it's annoying, thanks.

**Comment by aeonaura** [comment]
Same, It adds the "active node" storage space to the dead/old node.
![nodedash](https://user-images.githubusercontent.com/35913290/35497448-6adb9702-0487-11e8-9909-f6269185da9f.PNG)
It's mirroring the active one. Let me know how else I can help.

**Comment by sibblegp** [comment]
Deployed.
