### ISSUE TITLE
UPGRADE AVAILABLE

### ISSUE THREAD

**Issue by ne0ark** [sibblegp/Storj-Dashboard-Client#6]
It seems like that message is not going away. Is upgrade check working correctly?

**Comment by sibblegp** [comment]
The server in question will have to report using the latest client before the message will go away.  I have gotten no other complaints about the message not going away so you may not have properly upgraded or your server may not be reporting.

**Comment by ne0ark** [comment]
Ah, its server not reporting. Can we make it ignore server that is offline. There is no point in complaining about the server that is not reporting.

**Comment by sibblegp** [comment]
There is an open ticket for that.  I'm going to work on it after I finish the Windows client.

Sincerely,
George P. Sibble
