### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by ne0ark** [sibblegp/Storj-Dashboard-Client#7]
Do the time seem wrong? How does it calculate time?

**Comment by sibblegp** [comment]
Right now it is all pacific timezone.  I will look into calculating timezone based upon your system's timezone.

**Comment by henrikhjelm** [comment]
you can add a settings page to storjdash.com and fix it that way.

**Comment by mikebzh44** [comment]
+1 need a setting ;)

**Comment by georgemaxim** [comment]
+1 need a setting ;)

**Comment by JAC2703** [comment]
+1 its a pain with multiple machines in different timezones.

**Comment by JoeMittler** [comment]
+1 need a way to change timezones..

**Comment by sibblegp** [comment]
I just rolled out local timezone detection.  Dates/times are now shown based upon the timezone of your system.  Enjoy!
