### ISSUE TITLE
Clickable response Time

### ISSUE THREAD

**Issue by kocotech** [sibblegp/Storj-Dashboard-Client#8]
Dear GS.

for now the RT is not clickable, it would be nice if there is a graph displaying the response times. or all the response times in one graph (all the nodes a miner has)

kind regards,

Koelie

**Comment by sibblegp** [comment]
Since https://storjstat.com does this and is very popular, I didn't want to replicate features.

**Comment by kocotech** [comment]
Hey George,

now i need two tools to check my nodes , it would be nice if it was a one stop shop, the userbase of storjstat would slowely move to your dash because it provides way more information :)

**Comment by sibblegp** [comment]
That's an interesting point.  I'll consider that.  Thanks!

Sincerely,
George P. Sibble
